- name:
  yum:
    name: nginx
    state: latest
  become: true
  become_method: sudo

- name: Starting Nginx service
  service:
    name: nginx 
    enabled: yes
    state: started
  become: true
  become_method: sudo

- name: Copy with template nginx.conf file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755
  notify: nginx_restart
  become: true
  become_method: sudo

