- hosts: localhost
  connection: localhost

  vars: 
    mongodb_version: "3.4"
    mongo_src:
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-v3.4-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.4-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel55-v3.2-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.2-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-v3.2-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel55-v3.0-latest.tgz
      - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.0-latest.tgz
  tasks:
  - debug: msg={{ mongo_src | get_mongo_src(ansible_os_family, "7", mongodb_version ) }}
  




   
