Tomcat_links:
  8.0.47: "ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.0.47/bin/apache-tomcat-8.0.47.tar.gz"
  7.0.82: "ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz"
  9.0.2: "ftp://ftp.byfly.by/pub/apache.org/tomcat/tomcat-9/v9.0.2/bin/apache-tomcat-9.0.2.tar.gz"

Tomcat_link: "{{ Tomcat_links[tomcat_version] }}"
tomcat_version: 8.0.47 
